name: "📝 Documentation Update"
description: "Suggest improvements or corrections to the documentation."
title: "[Documentation Update]: "
labels: ["documentation", "enhancement"]
body:
  - type: textarea
    id: "issue_description"
    attributes:
      label: "Issue Description"
      description: "Provide a clear and concise description of the issue or area of improvement in the documentation."
      placeholder: "E.g., 'The installation steps for version X are missing a critical command.'"
    validations:
      required: true

  - type: textarea
    id: "suggested_change"
    attributes:
      label: "Suggested Change"
      description: "Outline the specific updates or corrections to be made in the documentation."
      placeholder: "E.g., 'Include the command `npm install <dependency>` in Step 3 of the installation section.'"
    validations:
      required: true

  - type: textarea
    id: "rationale"
    attributes:
      label: "Rationale"
      description: "Explain why this documentation update is necessary or beneficial. Include any relevant context or examples."
      placeholder: "E.g., 'This step is essential for successful installation and reduces confusion for new users.'"
    validations:
      required: false

  - type: dropdown
    id: "urgency"
    attributes:
      label: "Urgency Level"
      description: "Select the urgency level for implementing this documentation update."
      options:
        - "High"
        - "Medium"
        - "Low"
      default: "Low"
    validations:
      required: true
